### ISSUE TITLE
symbollic links get the absolute path stripped when extracted from cyphertite archives

### ISSUE THREAD

**Issue by csmiken** [conformal/cyphertite#29] opened 2013-07-03 17:10 UTC
$ ls -l test
lrwxr-xr-x  1 todd  todd  5 Apr 25 12:22 test -> /test
$ ct -cvf testln test
Generating filelist, this may take a few minutes...
Done! Initiating backup...
test
$ rm test
$ ct -xvf testln
file: /home/todd/.mdcache_todd/20130425-122240-testln version: 3 level: 0 block size: 262144 created: Thu Apr 25 12:22:40 2013
test
$ ls -l test
lrwx------  1 todd  todd  4 Apr 25 12:23 test -> test

$ ct -V
ct version: 1.5.4 CYPHERTITE_1_5_3-1-g5fbe1fe
Run-time versions:
 assl: 1.2.0
 clog: 0.6.3
 curl: libcurl/7.26.0 OpenSSL/1.0.1c zlib/1.2.3 libidn/1.26
 event: 2.0.21-stable
 exude: 0.7.2
 openssl: OpenSSL 1.0.1c 10 May 2012
 shrink: 0.5.2
 xmlsd: 0.10.0
O/S identification: OpenBSD-amd64-5.3 GENERIC#0

**Comment by davecgh** [comment] 2013-10-29 23:24
This is a duplicate of #54.

**Closed as completed by davecgh** 2013-10-29 23:24 UTC
Labels: bug
