### ISSUE TITLE
Files in folders with Swedish characters are not backed up (or can't be restored).

### ISSUE THREAD

**Issue by alphaleonis** [conformal/cyphertite#40] opened 2013-08-23 19:59 UTC
I created the following file/folder structure:
\BackupTest
--- äöå 
---|--- åäö.txt
--- åäö.txt

And created a backup using the Cypherite GUI (Windows).
Then I tried to extract the backup, which worked without any errors, except that the folder 'äöå' is empty.

If I try to navigate to that folder in the backup using the Cyphertite GUI while browsing backups I get the error message "Invalid Path". 

(I originally discovered this problem on "real" backups, where I am unable to restore all files, so this is a very serious problem for me)

**Comment by csmiken** [comment] 2013-08-26 19:37
Sorry to hear about this issue. I would like to look into it more. Can you provide what version of Cyphertite and what version of Windows you are using? Feel free to respond here or you can email support@cyphertite.com as a more private alternative.

**Comment by alphaleonis** [comment] 2013-08-26 19:57
Here is the version information printed by the CLI. I'm running Windows 8 Pro x64 English version.

cyphertite version: 1.6.2
Run-time versions:
 assl: 1.4.1
 clens: 0.0.6
 clog: 0.6.4
 curl: libcurl/7.25.0 OpenSSL/1.0.1c zlib/1.2.5
 event: 2.0.17-stable
 exude: 0.7.3
 openssl: OpenSSL 1.0.1c 10 May 2012
 shrink: 0.5.4
 xmlsd: 0.10.1
O/S identification: Microsoft Professional-amd64-6.2 (build 9200)

**Comment by owainga** [comment] 2013-09-17 22:20
I've just tried to reproduce this on Unix to try and narrow down the cause.

Unix (bitrig, specifically) with unicode characters works fine when creating an identical file structure to your example. The version was git master. I think this a problem with the windows client only. Our windows developers are looking into it.

**Comment by alphaleonis** [comment] 2013-10-03 13:26
Any news on this? It is a rather serious problem for me at the moment since all of my files are not being backed up.

**Comment by csmiken** [comment] 2013-10-03 19:08
We are looking into it. I will see if I can get a status update from our Windows developers today.

**Comment by csmiken** [comment] 2013-10-07 14:57
Here is a response/update from one of my developers:

It is incredibly fixable, and I will attempt to look at it this asap.... Strings require additional hoops with how we're set up to accommodate UTF8 vs Unicode vs ANSI.  Most Windows-only apps solve this pretty easily, but our applications require a bit more manual pre-processing.

**Comment by csmiken** [comment] 2014-03-03 20:45
This was a character-specific issue fixed as of Cyphertite 1.6.7.

**Closed as completed by csmiken** 2014-03-03 20:45 UTC
Labels: bug
